## 특징

+ 벡터 및 행렬 연산과 관련된 편리한 기능을 제공(선형 대수 관련)
+ 리스트에 비해 빠르고 메모리를 효율적으로 사용할 수 있는 배열(ndarray) 제공
+ 반복문 없이 데이터 배열에 대한 처리를 지원(인덱싱, 질의)
+ http://www.numpy.org

In [2]:
import numpy as np

### 1. 1차원 배열

In [12]:
a1 = [1, 2, 3, 4, 5, 10, 20, "가", "나"]
print(a1)
print(type(a1))
# print(a1.shape)
# print(a1.dtype)

[1, 2, 3, 4, 5, 10, 20, '가', '나']
<class 'list'>


In [10]:
a2 = np.array([1, 2, 3, 4, 5, 10, 20, "가", "나"])
print(a2)
print(type(a2))
print(a2.shape)
print(a2.dtype)

['1' '2' '3' '4' '5' '10' '20' '가' '나']
<class 'numpy.ndarray'>
(9,)
<U11


In [15]:
a3 = np.array([1, 2, 3, 4, 5, 10, 20, "30", "40"], float)
print(a3)
print(a3.dtype)

[ 1.  2.  3.  4.  5. 10. 20. 30. 40.]
float64


In [20]:
a4 = np.dtype(">i4")
print(a4)
print(a4.name)

a5 = np.dtype(">i8")
print(a5)
print(a5.name)

>i4
int32
>i8
int64


In [23]:
# 벡터화 연산

data1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(data1 * 2)
# print(data1 - 2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [26]:
data2 = np.array(data1)
print(data2 * 2)
print(data2 - 2)
print(data2 + 2)

[ 0  2  4  6  8 10 12 14 16 18]
[-2 -1  0  1  2  3  4  5  6  7]
[ 2  3  4  5  6  7  8  9 10 11]


In [28]:
# 인덱스 접근
print(data2[0], data2[1])

0 1


### 2. 2차원 배열

In [31]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print(arr)
print(arr.shape)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int32


In [35]:
# 접근
print(arr[0])
print(arr[0][1])
print("-------------------")
print(len(arr))
print(len(arr[0]))

[1 2 3]
2
-------------------
2
3
